name: make-lint.yml
on: push
jobs:
  make-lint:
    runs-on: ubuntu-latest 
    steps:
       - uses: actions/checkout@v2
       - name: npm install
         run: | 
           make install
       - name: make-lint
         run: | 
           make-lint
      